extends:
  - 'next/core-web-vitals'
  - 'plugin:import/recommended'
  - 'plugin:import/warnings'
  - 'plugin:react-hooks/recommended'
  - 'prettier'

rules:
  'import/order':
    - warn
    - alphabetize:
        order: asc
      pathGroups:
        - pattern: '@alias/**'
          group: parent
          position: before
  no-unused-vars:
    - warn
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
      caughtErrorsIgnorePattern: '^_'
      destructuredArrayIgnorePattern: '^_'
