import { css } from '@emotion/react'
import styled from '@emotion/styled'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>FlipFlap</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Main>
        <h1
          css={css`
            font-size: 64px;
          `}
        >
          FlipFlap
        </h1>
      </Main>

      <Footer>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <Logo>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </Logo>
        </a>
      </Footer>
    </Container>
  )
}

const Container = styled.div`
  padding: 0 32px;
  display: flex;
  min-height: 100vh;
  flex-direction: column;
`

const Main = styled.main`
  display: flex;
  flex-direction: column;
  align-items: center;
  flex-grow: 1;
  justify-content: center;
  align-items: center;
`

const Footer = styled.footer`
  display: flex;
  border-top: 1px solid #eaeaea;
  justify-content: center;
  align-items: center;
  padding: 32px 0;
`

const Logo = styled.span`
  height: 16px;
  margin-left: 8px;
`

export default Home
