name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  packages:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: yarn
      - name: Yarn Install
        run: yarn install --frozen-lockfile
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: yarn
      - name: Yarn Install
        run: yarn install --frozen-lockfile
      - name: Yarn Lint
        run: yarn lint
  type-check:
    name: Typecheck
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: yarn
      - name: Yarn Install
        run: yarn install --frozen-lockfile
      - name: Yarn Typecheck
        run: yarn typecheck
  format:
    name: Format
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: yarn
      - name: Yarn Install
        run: yarn install --frozen-lockfile
      - name: Yarn Format
        run: npx prettier --check .
