name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  GITEA_SSH_URL: 'ssh://git@git.trap.jp:2200/FlipFlap/FlipFlap-UI.git'
  NEXT_PUBLIC_BASE_URL: ${{ secrets.API_BASE_URL }}
  API_DOMAIN: ${{ secrets.API_DOMAIN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  packages:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: yarn
      - name: Yarn Install
        run: yarn install --frozen-lockfile
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: yarn
      - name: Yarn Install
        run: yarn install --frozen-lockfile
      - name: Yarn Lint
        run: yarn lint
  type-check:
    name: Typecheck
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: yarn
      - name: Yarn Install
        run: yarn install --frozen-lockfile
      - name: Yarn Typecheck
        run: yarn typecheck
  format:
    name: Format
    runs-on: ubuntu-latest
    needs: [packages]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: yarn
      - name: Yarn Install
        run: yarn install --frozen-lockfile
      - name: Yarn Format
        run: yarn lint:format

  push-to-gitea:
    name: Push to Gitea
    runs-on: ubuntu-latest
    needs: [packages, lint, type-check, format]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: yarn
      - name: Yarn Install
        run: yarn install --frozen-lockfile
      - name: Cache Next
        uses: actions/cache@v3
        with:
          path: .next
          key: ${{ runner.os }}-next-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-next-
      - name: Build
        run: yarn build

      - name: Set Config
        run: |
          echo "${{ secrets.GITEA_TOKEN }}" > ~/deploy_key.pem
          chmod 600 ~/deploy_key.pem
          git config --global user.name "github"
          git config --global user.email "github@actions"
      - name: Commit (include build)
        run: |
          git add .next -f
          git add node_modules -f
          git commit -m "[build] ${{ github.event.head_commit.id }}"
      - name: Push Changes
        env:
          GIT_SSH_COMMAND: ssh -i ~/deploy_key.pem -o StrictHostKeyChecking=no -F /dev/null
        run: |
          git fetch --unshallow origin
          git push -f ${{ env.GITEA_SSH_URL }} main:master
